// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using desafio_03.Models;

#nullable disable

namespace desafio_03.Migrations
{
    [DbContext(typeof(TurnoverContext))]
    [Migration("20241024010906_AddRoleToUsuarios")]
    partial class AddRoleToUsuarios
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("desafio_03.Models.Concierto", b =>
                {
                    b.Property<int>("ConciertoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ConciertoID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ConciertoId"), 1L, 1);

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime");

                    b.Property<string>("Lugar")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("ConciertoId");

                    b.ToTable("Conciertos");
                });

            modelBuilder.Entity("desafio_03.Models.Entrada", b =>
                {
                    b.Property<int>("EntradaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("EntradaID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EntradaId"), 1L, 1);

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCompra")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("SeccionId")
                        .HasColumnType("int")
                        .HasColumnName("SeccionID");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int")
                        .HasColumnName("UsuarioID");

                    b.HasKey("EntradaId");

                    b.HasIndex("SeccionId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Entradas");
                });

            modelBuilder.Entity("desafio_03.Models.HistorialCompra", b =>
                {
                    b.Property<int>("HistorialId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("HistorialID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HistorialId"), 1L, 1);

                    b.Property<int>("EntradaId")
                        .HasColumnType("int")
                        .HasColumnName("EntradaID");

                    b.Property<DateTime>("FechaCompra")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int")
                        .HasColumnName("UsuarioID");

                    b.HasKey("HistorialId")
                        .HasName("PK__Historia__975206EF0EB9ED47");

                    b.HasIndex("EntradaId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("HistorialCompras");
                });

            modelBuilder.Entity("desafio_03.Models.Seccione", b =>
                {
                    b.Property<int>("SeccionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("SeccionID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SeccionId"), 1L, 1);

                    b.Property<int>("CantidadDisponible")
                        .HasColumnType("int");

                    b.Property<int>("ConciertoId")
                        .HasColumnType("int")
                        .HasColumnName("ConciertoID");

                    b.Property<string>("NombreSeccion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("SeccionId")
                        .HasName("PK__Seccione__18B61621A0B9F74A");

                    b.HasIndex("ConciertoId");

                    b.ToTable("Secciones");
                });

            modelBuilder.Entity("desafio_03.Models.Usuario", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("UsuarioID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UsuarioId"), 1L, 1);

                    b.Property<string>("Contraseña")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("UsuarioId");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("desafio_03.Models.Entrada", b =>
                {
                    b.HasOne("desafio_03.Models.Seccione", "Seccion")
                        .WithMany("Entrada")
                        .HasForeignKey("SeccionId")
                        .IsRequired()
                        .HasConstraintName("FK_Seccion_Entradas");

                    b.HasOne("desafio_03.Models.Usuario", "Usuario")
                        .WithMany("Entrada")
                        .HasForeignKey("UsuarioId")
                        .IsRequired()
                        .HasConstraintName("FK_Usuario_Entradas");

                    b.Navigation("Seccion");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("desafio_03.Models.HistorialCompra", b =>
                {
                    b.HasOne("desafio_03.Models.Entrada", "Entrada")
                        .WithMany("HistorialCompras")
                        .HasForeignKey("EntradaId")
                        .IsRequired()
                        .HasConstraintName("FK_Entrada_Historial");

                    b.HasOne("desafio_03.Models.Usuario", "Usuario")
                        .WithMany("HistorialCompras")
                        .HasForeignKey("UsuarioId")
                        .IsRequired()
                        .HasConstraintName("FK_Usuario_Historial");

                    b.Navigation("Entrada");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("desafio_03.Models.Seccione", b =>
                {
                    b.HasOne("desafio_03.Models.Concierto", "Concierto")
                        .WithMany("Secciones")
                        .HasForeignKey("ConciertoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Concierto_Secciones");

                    b.Navigation("Concierto");
                });

            modelBuilder.Entity("desafio_03.Models.Concierto", b =>
                {
                    b.Navigation("Secciones");
                });

            modelBuilder.Entity("desafio_03.Models.Entrada", b =>
                {
                    b.Navigation("HistorialCompras");
                });

            modelBuilder.Entity("desafio_03.Models.Seccione", b =>
                {
                    b.Navigation("Entrada");
                });

            modelBuilder.Entity("desafio_03.Models.Usuario", b =>
                {
                    b.Navigation("Entrada");

                    b.Navigation("HistorialCompras");
                });
#pragma warning restore 612, 618
        }
    }
}
