//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace desafio_02_e04
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetallesPedidos
    {
        public int DetallePedidoId { get; set; }
        public int PedidoId { get; set; }
        public int MenuId { get; set; }
        public int Cantidad { get; set; }
        public decimal Precio { get; set; }
    
        public virtual Menus Menus { get; set; }
        public virtual Pedidos Pedidos { get; set; }
    }
}
